//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3_WorkflowConsoleApp.MyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SecretNumber", ReplyAction="http://tempuri.org/IService1/SecretNumberResponse")]
        Assignment3_WorkflowConsoleApp.MyService.SecretNumberResponse SecretNumber(Assignment3_WorkflowConsoleApp.MyService.SecretNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SecretNumber", ReplyAction="http://tempuri.org/IService1/SecretNumberResponse")]
        System.Threading.Tasks.Task<Assignment3_WorkflowConsoleApp.MyService.SecretNumberResponse> SecretNumberAsync(Assignment3_WorkflowConsoleApp.MyService.SecretNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkNumber", ReplyAction="http://tempuri.org/IService1/checkNumberResponse")]
        Assignment3_WorkflowConsoleApp.MyService.checkNumberResponse checkNumber(Assignment3_WorkflowConsoleApp.MyService.checkNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkNumber", ReplyAction="http://tempuri.org/IService1/checkNumberResponse")]
        System.Threading.Tasks.Task<Assignment3_WorkflowConsoleApp.MyService.checkNumberResponse> checkNumberAsync(Assignment3_WorkflowConsoleApp.MyService.checkNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SecretNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SecretNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int lower;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int higher;
        
        public SecretNumberRequest() {
        }
        
        public SecretNumberRequest(int lower, int higher) {
            this.lower = lower;
            this.higher = higher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SecretNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SecretNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SecretNumberResult;
        
        public SecretNumberResponse() {
        }
        
        public SecretNumberResponse(int SecretNumberResult) {
            this.SecretNumberResult = SecretNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class checkNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int userNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int SecretNum;
        
        public checkNumberRequest() {
        }
        
        public checkNumberRequest(int userNum, int SecretNum) {
            this.userNum = userNum;
            this.SecretNum = SecretNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class checkNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string checkNumberResult;
        
        public checkNumberResponse() {
        }
        
        public checkNumberResponse(string checkNumberResult) {
            this.checkNumberResult = checkNumberResult;
        }
    }
}
